### ISSUE TITLE
Google home rechargement config

### ISSUE THREAD

**Issue by 889laurent** [proknx/realknx#4]
Je voudrais savoir comment recharger la config dans google home après avoir fait des modifs dans ETS ?

**Comment by jenskastensson** [comment]
Do this:
1. Restart realKNX from the main menu.
2. Unlink and then re-link the realKNX Google action. (This step could in fact do the job if you want to give it a try)

For info: in the next release (Q1 2018) we will add a refresh-Google-devices-button.

Let me know if this solves your problem.

**Comment by 889laurent** [comment]
Merci pour votre réponse. J’ai délier et relier ensuite le fournisseur realknx dans google home pour prendre en compte les modifications. Mais il faut ensuite relier le matériel a des pièces. J’attend avec impatience le bouton refresh.

Cordialement

**Comment by proknx** [comment]
Fixed in realKNX v3.2 (Node-RED v1.2.3)
