### ISSUE TITLE
Alexa en francais

### ISSUE THREAD

**Issue by 889laurent** [proknx/realknx#8]
Amazon m’a envoyé un boitier alexa pour test. Je ne trouve pas le skill proknx. Il y a t’il une méthode particulière pour le récupérer?

**Comment by proknx** [comment]
Bonsoir, il faut un compte Amazon en Angleterre où Allemagne. Moi j'ai un
compte sur l'adresse :  10 Downings street, Londre 😙

**Comment by 889laurent** [comment]
Merci, mais ca marche en francais?

**Comment by jenskastensson** [comment]
Non Alexa parle que anglais et allemand pour le moment. Français :
Peut-être en Avril 2018 selon certain blogs sur internet.

**Comment by 889laurent** [comment]
J’ai recu de la part de amazon un boitier de test! Et il parle francais

**Comment by proknx** [comment]
Ah cool, vous êtes premier à tester !

**Comment by 889laurent** [comment]
j'aimerai bien tester avec proknx, mais si je prend un compte a l'étranger, je pense qu'il sera dans la langue !
comment récupérer le skill en français de proknx ?

**Comment by jenskastensson** [comment]
Pour être honnête je ne sais pas , il faut peut être demande Amazon comment
faire. Je vois que Allemand, Anglais (x5) et Japonais mais pas francais.
desolé

**Comment by 889laurent** [comment]
Malheureusement amazon m’a répondu que pas possible pendant la période de test

**Comment by jenskastensson** [comment]
Merci quand même pour l'effort!

**Comment by jenskastensson** [comment]
Alexa skill is online since a few months
